### PR TITLE
- sendImage can now functional.

### PR DESCRIPTION
**Pull request by shinznatkid**
Reference: http://altrepo.eu/git/line-protocol/blob/master/line-protocol.md

### CODE REVIEW

**Comment by carpedm20** [comment]
@shinznatkid Thanks, I test your code and assure that your code works well :+1:

**Comment by anusoft** [comment]
I've got this error, and cannot find returning id from sendMessage from anywhere in code.

```
Traceback (most recent call last):
  File "echobot.py", line 232, in <module>
    contact.sendImage('.tmp.image')
  File "/usr/local/lib/python2.7/dist-packages/line-0.4.1-py2.7.egg/line/models.py", line 107, in sendImage
    pprint.pprint(self._client.sendMessage(message).id)
AttributeError: 'NoneType' object has no attribute 'id'

```

**Comment by anusoft** [comment]
You need to change client.py to return sendMessage also

```
    def sendMessage(self, message, seq=0):
        """Send a message
        
        :param message: LineMessage instance to send
        """
        if self._check_auth():
            try:
                return self._sendMessage(message, seq)
            except TalkException as e:
                self.updateAuthToken()
                try:
                    return self._sendMessage(message, seq)
                except Exception as e:
                    self.raise_error(e)

                    return False
```

**Comment by carpedm20** [comment]
Thanks @anusoft

**Pull request merged**
