### PR TITLE
Use https:// for communication with LINE servers.

### PR DESCRIPTION
**Pull request by dtzWill**

### CODE REVIEW

**Comment by CYBAI** [comment]
According to the [unofficial line-protocol](http://altrepo.eu/git/line-protocol.git/blob/afd428c0ab9173a5eed15c24496dff577c73b25e:/line-protocol.md#l20), I think it's able to use both `http://` and `https://`.

**Comment by carpedm20** [comment]
I think this is unnecessary because

1. We can see plain request/response when we use http
2. https:// takes more time to communicate (because it needs encryption and more packets)

If http is not working, then we should change it to https. If you have other opinion, feel free to share it.

**Comment by dtzWill** [comment]
Good point about ability to see protocol in action, and only a personal preference--  "http://" definitely seems to be working for me.

Don't feel strongly enough about it to push for it as the default :).  Thanks for the response and comments!

**Comment by carpedm20** [comment]
Great :smile: Then this issue will be closed until **http://** won't work properly

**Comment by theawangatang** [comment]
http:// won't work properly anymore

**Pull request closed without merging**
